// Generated by dia2code
#ifndef CARACTERISTIQUES__H
#define CARACTERISTIQUES__H

/// class Caracteristiques -
class Caracteristiques {
  // Attributes
protected:
  int sante;
  int attaque;
  int defense;
  int initiative;
  int vitesse;
  // Operations
public:
  Caracteristiques (int sante = 0 , int attaque = 0,                    int defense = 0,
                    int initiative = 0, int vitesse = 0);
  ~Caracteristiques ();
  // Setters and Getters
  int getSante() const;
  void setSante(int sante);
  int getAttaque() const;
  void setAttaque(int attaque);
  int getDefense() const;
  void setDefense(int defense);
  int getInitiative() const;
  void setInitiative(int initiative);
  int getVitesse() const;
  void setVitesse(int vitesse);
};

#endif
