// Generated by dia2code
#ifndef COMBAT__H
#define COMBAT__H

// Etat
/// class Combat - 
class Combat : public Etat {
  // Associations
  // Attributes
private:
  Action action;
  int tour;
  // Operations
public:
  Combat ();
  ~Combat ();
  bool choixAction (Action action);
  bool applyAction (Action action);
  // Setters and Getters
};

#endif
