// Generated by dia2code
#ifndef DEPLACEMENT__H
#define DEPLACEMENT__H

// Etat
/// class Deplacement - 
class Deplacement : public Etat {
  // Associations
  // Attributes
private:
  Map map;
  // Operations
public:
  Deplacement ();
  ~Deplacement ();
  /// Renvoie Faux si deplacement impossible
  /// @param jouant		(???) 
  /// @param position		(???) 
  bool deplacerJoueur (Joueur jouant, Position position);
  // Setters and Getters
};

#endif
