// Generated by dia2code
#ifndef ECHANGE__H
#define ECHANGE__H

// Etat
/// class Echange - 
class Echange : public Etat {
  // Associations
  // Attributes
private:
  std::vector<item> item;
  // Operations
public:
  Echange ();
  ~Echange ();
  bool acheter (Item item);
  bool terminerEchange ();
  // Setters and Getters
};

#endif
