// Generated by dia2code
#ifndef ENTITE__H
#define ENTITE__H

#include "Caracteristiques.h"
#include "Position.h"

/// class Entite - 
class Entite {
  // Associations
  // Attributes
private:
  Caracteristiques caracteristiques;
  Position position;
  // Operations
public:
  Entite();
  ~Entite();
  // Setters and Getters
};

#endif
