// Generated by dia2code
#ifndef ETAT__H
#define ETAT__H

#include "Joueur.h"

/// class Etat - 
class Etat {
  // Associations
  // Attributes
private:
  std::vector<Joueur> joueurs;
  std::vector<Joueur> ennemis;
  /// Joueur qui joue actuellement
  Joueur jouant;
  int tour;
  bool multijoueur;
  bool terminerJeu;
  // Operations
public:
  Etat ();
  ~Etat ();
  void init ();
  int initJoueur (Joueur joueur);
  int changeJouant (Joueur joueurSuivant);
  int transitionEtat (Etat etat);
  // Setters and Getters
};

#endif
