// Generated by dia2code
#ifndef ITEM__H
#define ITEM__H

/// class Item - 
class Item {
  // Attributes
public:
  Caracteristique bonus;
private:
  String nom;
  int prix;
  // Operations
public:
  Item ();
  ~Item ();
  // Setters and Getters
};

#endif
