// Generated by dia2code
#ifndef JOUEUR__H
#define JOUEUR__H

/// class Joueur - 
class Joueur {
  // Associations
  // Attributes
private:
  String nom;
  Entite entite;
  int monet;
  // Operations
public:
  Joueur (String nom);
  ~Joueur ();
  // Setters and Getters
};

#endif
