// Generated by dia2code
#ifndef JOUEUR__H
#define JOUEUR__H

#include <iostream>
#include "Entite.h"

/// class Joueur - 
class Joueur {
  // Associations
  // Attributes
private:
  String nom;
  Entite entite;
  int monnaie;
  // Operations
public:
  Joueur (std::string nom);
  ~Joueur ();
  void ajoueMonnaie(int monnaie);
  // Setters and Getters
};

#endif
