// Generated by dia2code
#ifndef MAP__H
#define MAP__H

#include "Obstacle.h"

/// class Map - 
class Map {
  // Associations
  // Attributes
private:
  Grille grille;
  std:vector<Obstacle> obstacles;
  // Operations
public:
  Map();
  ~Map();
  // Setters and Getters
};

#endif
