// Generated by dia2code
#ifndef OBSTACLE__H
#define OBSTACLE__H

#include "Position.h"

/// class Obstacle - 
class Obstacle {
  // Attributes
private:
	Position* position;
	int taille[2];
  // Operations
public:
  Obstacle (int a=0,int b=0,Position* position = new Position());
  ~Obstacle ();
  // Setters and Getters
  int getX() const;
  int getY() const;

};

#endif
