// Generated by dia2code
#ifndef OBSTACLE__H
#define OBSTACLE__H

/// class Obstacle - 
class Obstacle {
  // Attributes
private:
  Position position;
  static int[2] taille;
  // Operations
public:
  Obstacle ();
  ~Obstacle ();
  // Setters and Getters
};

#endif
