// Generated by dia2code
#ifndef ORDRE__H
#define ORDRE__H

/// class Ordre - 
class Ordre {
  // Attributes
private:
  Joueur Jouant;
  Joueur joueurSuivant;
  // Operations
public:
  Order ();
  ~Order ();
  Joueur JoueurSuivant ();
  bool supprJoueur (Joueur joueur);
  AjoutJoueur (Joueur joueur);
  std::Vector<String> getOrdre ();
  // Setters and Getters
};

#endif
