// Generated by dia2code
#ifndef POSITION__H
#define POSITION__H

#include <iostream>

/// class Position - 
class Position {
  // Attributes
private:
  std::string orientation;
protected:
  int x;
  int y;
  // Operations
public:
  Position (int x = 0, int y = 0,std::string orientation = "North");
  ~Position ();
  /// deplacement relatif
  /// @param x		(???) 
  /// @param y		(???) 
  void deplacer (int x, int y);
  void rotate (std::string rotation);
  /// placement absolu
  /// @param x		(???) 
  /// @param y		(???) 
  void placer (int x, int y);
  // Setters and Getters
  int getX() const;
  void setX(int x);
  int getY() const;
  void setY(int y);
  std::string getOrientation() const;
};

#endif