// Generated by dia2code
#ifndef ZONE__H
#define ZONE__H

/// class Zone - 
class Zone {
  // Attributes
private:
  Position position;
  int[2] taille;
  String type;
  // Operations
public:
  Zone ();
  ~Zone ();
  // Setters and Getters
};

#endif
